project:
  type: book
  output-dir: docs

book:
  title: "The Political Economy of Institutional Change and Social Blocs in Switzerland: a Neorealist Approach"
  subtitle: "Master in the Political Economy of Capitalism, University of Geneva"
  author:
    - name: Celâl Güney
    - name: "Supervisor: Professor Bruno Amable"
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - part1.qmd
    - conclusion_appendix.qmd
    - autoanalyse.qmd
    - references.qmd

title-block-banner: false

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    include-in-header: 
      text: |
          \usepackage{tabularray}
          \usepackage{float}
          \usepackage{codehigh}
          \usepackage{graphicx}
          \usepackage[normalem]{ulem}
          \UseTblrLibrary{booktabs}
          \NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
          \newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
          \newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
    documentclass: scrreport
    link-citations: TRUE
    toc: true
    toc-depth: 3
    lof: true
    lot: true
  docx:
    reference-doc: custom-reference.docx


editor: visual


