---
title: "Income and Voting at the Communal Level in Switerland: 2011-2019"
author: "Celâl Güney"
format: html
editor: visual
---
```{r}
setwd("C:/Users/celal/OneDrive/Bureau/master-thesis/data/ofs_communal_voting")
library(tidyverse)
```

```{r}
library(readr)
plr_share_2011 <- read_delim("C:/Users/celal/OneDrive/Bureau/master-thesis/data/ofs_communal_voting/plr_share_2011.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
plr_share_2011$plr_share <- as.numeric(plr_share_2011$plr_share)
```

```{r}
plr_share_2011$plr_share <- as.numeric(plr_share_2011$plr_share)
```

```{r}
income_com_2011 <- read_delim("C:/Users/celal/OneDrive/Bureau/master-thesis/data/ofs_communal_voting/income_com_2011.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)



income_2011 <- 
  income_com_2011 %>% 
  dplyr::select(GEO_ID, GEO_NAME ,VARIABLE, VALUE) %>% 
  pivot_wider(names_from = "VARIABLE",
              values_from = "VALUE") %>% 
  rename(
    net_income_mio = "Revenu net, en mio. de francs",
    net_income_per_hab = "Revenu net par habitant/-e, en francs"
  )

```

```{r}
data_2011 <- 
  income_2011 %>% 
  left_join(plr_share_2011, by = c("GEO_NAME" = "Regionsname"))
```


```{r}
data_2011 <- 
data_2011 %>% 
  mutate(perc = ntile(net_income_per_hab, 100),
         decile = ntile(net_income_per_hab, 10))

data_2011 %>% 
  group_by(perc) %>% 
  summarise(avg_share_plr = mean(plr_share, na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(aes(x = perc, y = avg_share_plr))+
  geom_point()+
  geom_line()


```

