# Abstract {.unnumbered}

What were the political conditions and social bases for a neoliberal transformation of the Swiss socio-economic model in the last decades? The present master thesis seeks to explore the social bases behind the transformation and stability of the Swiss socio-economic model since the 80s. As a first step, long-run analyses of the socio-economic determinants of party support, political leaning and policy preferences are conducted. The results show evidence that, regarding party support, Switzerland's political landscape appears to be structured by a brahmin left versus merchant right divide, as theorized by @piketty_capital_2019. However, the results for political leaning show that, while right leaning evolved into a merchant pattern, left leaning became gradually endorsed by upper-middle income and high education groups. Finally, the results from a latent class analysis aimed at identifying the recomposition of the Swiss social blocs in the late 90s are presented. The selected model divides the late 90s' Swiss population into twelve socio-political groups, and the different strategies that could have aggregated these clusters into social blocs are assessed. Using the concepts and methods of neorealism [@amable_leconomie_2005; @amable_neorealist_2008], the objective of this master thesis is to provide the first steps into a broader analysis of the political economy of institutional change in Switzerland.



