# Introduction

```{r}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
library(haven)
library(quarto)
library(sjlabelled)

```

Switzerland represents an interesting case study for the analysis of institutional change. Despite some widespread *clichés*, such as the supposed slowness and rigidity of the Swiss political system, the country experienced important institutional, economic, as well as political change in the last decades. The Swiss model of capitalism is also difficult to classify in the varieties of capitalism (VoC) framework. @hall_varieties_2001 typically ranked Switzerland among the coordinated market economies (CMEs). Despite the structural weakness of the Swiss federal state, the low density of labor union and the predominance of business interests, Switzerland's economy developed various non-market and non-competitive coordination mechanisms throughout the 20th century. One can think of, for instance, the cartelization of major Swiss industries which was actively supported by the state through public subsidies in the interwar period [see @boillat_controler_2011 for the case of the Swiss watch industry] or the creation and expansion of the Swiss welfare state after the Second World war, even though the latter remains small compared to other welfare state regimes [@obinger_federalism_1998]. Swiss corporate governance also displayed strong differences from a market-based, shareholder-oriented system which typically prevails in Anglo-Saxon countries. Until the mid-1980s, Swiss corporate governance was characterized by self-regulation by private actors with minimal legal framework, protection and "selective protectionism" (*Vinkulierung*) in favor of Swiss shareholders and blockholders and strong cooperation between business actors, associations and networks [@mach_transformations_2007].

According to Katzenstein [-@katzenstein_small_1985], small European states like Switzerland were likely to develop such coordinated and corporatist institutions. In fact, small domestic markets, international competitive pressure and the structural weakness of small states make the latter likely to develop some forms of "democratic corporatism". But among democratic corporatism systems, Katzenstein still stressed that Switzerland could be classified as a "liberal variant" of democratic corporatism due to weak labor unions and the dominance of employer's associations.

Therefore, Swiss capitalism represents a peculiar case with both liberal and non-liberal institutions: weak labor union density and strong business side; labor market flexibility and weak state intervention are all features that could sort the Swiss case into the "liberal market economy" type of capitalism (LMEs). The uniqueness of the Swiss model, which combined both strong liberal and coordinated elements, led @trampusch_switzerland_2011 to talk about the "Swiss hybrid model" (SHM).

However, since the neoliberal turning point of the late 20th century, the SHM is under pressure and is gradually mutating into the (neo)liberal type of capitalism [@trampusch_switzerland_2011]. The so-called "structural reforms" advocated by international organizations such as the OECD, but also promoted internally by various Swiss actors, led to subsequent waves of neoliberal reforms in almost all institutional areas. Neoliberal reforms went from competitive policies such as the Swiss Cartel Act ("Carta") of 1995, which aimed at limiting or even suppressing cartels and to strengthen competition, to privatizations like the partial privatization of the PTT (*Poste, téléphone et télégraphe*) in the late 1980s. Regarding corporate governance, the new Stock Corporation law of 1991 and the Federal Act on Stock Exchange and Securities Trading (SESTA) of 1995, among other reforms, marked the beginning of the convergence of the so-called traditional *"Forteresse des Alpes"* ("Alps Fortress") Swiss financial and corporate governance system towards the liberal Anglo-Saxon model [@david_forteresse_2015].

The neoliberal transformation of the Swiss socio-economic model is nonetheless far from complete and has met some resistance, according to some observers. On the one hand, the Swiss advocates of neoliberalism are still unsatisfied with the progress of the reforms and are keen on underlying the remaining rigidities of the Swiss Hybrid Model. In that respect, Gerhard Schwarz, director of the neoliberal think thank *Avenir Suisse* between 2011 and 2015, and co-author of the so-called "white books", which were the first manifesto promoting a neoliberal transformation of the Swiss model in the 1990s [@leutwiler_politique_1991; @hauser_ayons_1996], declared in 2015:

> "It is absurd to believe that we live in a liberal society. The Swiss politico-economic system is mixed, as evidenced by the share of the state, compulsory levy, of 40%. The production of norms and reglementations grows exponentially. I am always surprised by the amount of people who still believe that we are in a neoliberal world. This is a *fake news*. The size of the state grows and the autonomony of the individual declines." [@noauthor_gerhard_2019, *my translation*]

On the other hand, the OECD still underlines the "barriers to free trade and competition in the domestic market" and the overdue of the pension reforms [@oecd_oecd_2022, p.12]. 

The extent to which the Swiss model will complete its mutation towards a neoliberal model represents thus a fundamental issue for the years to come. A thorough and non-normative analysis of the path taken by the Swiss model since the crisis of the 1990s is thus duly needed and is behind the motivation of the present paper. What kind of social base made this neoliberal transformation of the Swiss socio-economic model possible in the last decades? Is this social base stable enough to complete this transformation? The aim of this essay is to conduct an analysis which would constitute a first step into a broader analysis of the political economy of institutional change in Switzerland. Far from the normative approach of mainstream economics, for which structural reforms simply constitute the sole and evident path towards its ideal model of perfect competition purged from rigidities, the methods and theory employed here are extensively based on the political economy approach of institutional change developed by Amable and Palombarini [-@amable_leconomie_2005; -@amable_neorealist_2008]. 

Since the break-up of the Post-war "historical compromise" between the Swiss Socialist Party (SSP) and the traditional right parties during the so-called "decade of all dangers" of the 90s [@boschetti_conquete_2007], the neoliberal transformation of the HSM was also followed, in the political scene, by the rise of the Swiss People Party (SVP), one of the most successful far-right populist parties in Europe. The electoral success of the SVP marked a strong destabilization of the traditional right bloc, which entered a phase of "cacophonic" crisis [@meuwly_liberte_2008] which still persists in the early 2020s.

After assessing the political and economic stability of the Swiss socio-economic model in the last decades, an empirical analysis of the structure and evolution of the Swiss social blocs since the 90s will be conducted in two parts. On the one hand, a long-run analysis of voting outcomes depending on socio-economic characteristics is conducted. The objective is to identify the social structure of the support for each main Swiss party and how the latter evolved from the 1980s to the 2020s. This part offers the opportunity to test findings of the literature about the links between socio-demographic characteristics, voting outcomes and political cleavages.

These transformations are of peculiar interest, especially because Switzerland is famous for its economic performance and political stability.

## The growing importance of political cleavages, social conflict and institutional change in political economy

Part of the recent political economy literature developed a tremendous analysis of the long-run transformations of political cleavages in almost all democratic countries around the globe. Following the now well-known success of inequality studies in economics and social sciences since the work of, naturally, @piketty_capital_2014 but also of @milanovic_global_2016 and others, economists are recently shifting their attention towards social conflict and political cleavages within capitalist economies.

One possible explanation of this sudden interest could be the following paradox: increasing inequality and neoliberal reforms which took place in the last decades did not pave the way mechanically for growing support for redistribution or left-wing parties. The same paradox could also be stressed for climate change since green parties were not relatively so successful despite the growing emergencies associated with environmental issues. More generally, the extent to which social and environmental issues translate into political conflict is of interest in the current age of "polycrisis". The multiplication of social and environmental crises puts into question the extent to which they can be resolved through political mediation.

This sudden interest thus gave birth to an ambitious project mostly conducted by economists under the supervision of Piketty. @gethin_political_2021 give a wide and broad analysis of political preferences as functions of socio-economic factors such as income, education, wealth, gender, religion and so on. This kind of project shows that economists are tackling with a subject that political scientists have been studying for decades, at least from @lipset_party_1967.

The main findings of @gethin_political_2021 can be summarized as follow: after the post-war period, political cleavages were structured around a single left-right axis structured around class conflict over economic issues. The support for the left was based on average on low income and education voters whereas the support for the right was correlated positively with income and education. Then, an "educational shift" took place in the 1980s and the vote for the left became positively associated with education, leading to a shift from "class-based" conflict to a "multi-party" structured around class and educational cleavages. The latter is reminiscent of what Inglehart [-@inglehart_silent_1971; -@inglehart_culture_1990] called the cleavage around "Postmaterialist" values which appeared as a result of growing material security.

Inequality studies thereby gave birth to a renewed interest for political conflict in economics and political economy. However, this revival of attention among economists is not only the result of the inequality paradox, but also a consequence of the willingness of various economic theories and schools of thought to explain institutional change. In fact, rising inequalities in the last decades was mainly the result of important institutional change, oriented towards so-called neoliberal or structural reforms *cit*. For instance, Régulation Theory (RT), originally focused on explaining the crisis of Fordism in the 1970s, developed a theoretical framework aimed at identifying accumulation regimes, their mode of regulation as well as their evolution, crises and successions [@aglietta_regulation_1997; @boyer_economie_2015]. Although the interactions between politics, the economy and institutions were not the original objective of RT, some economists trained and influenced by this school of thought elaborated a theory of institutional which analyzes political, institutional and economic dynamics as a totally. In this regard, the decisive step to this rather new theory of the political economy of institutional change was made Amable and Palombarini [-@amable_leconomie_2005; -@amable_neorealist_2008] and their neorealist approach.

## Literature Review
