# Summary



```{r}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
library(haven)
library(quarto)
library(sjlabelled)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(ade4)
library(questionr)
library(foreign)
library(MASS)
library("effects")
library(ordinal)

```

```{r}
rm(list = ls())
selects1995 <- read_sav("data/64_Selects1995_PES_Data_v1.2.sav")
selects1995cum <- read_sav("data/495_Selects_CumulativeFile_Data_1971-2019_v2.3.0.sav") %>% 
  filter(year == 1995)
```


```{r}
## adding variables from cumulative dataset to original dataset

selects1995 <- 
  selects1995 %>% 
  mutate(
    income = selects1995cum$income,
    income_hh = selects1995cum$income_hh,
    educ = selects1995cum$educ
  ) %>% 
  rename(
    inc = "q179",
    education = "q103",
    lr = "q35",
    occupation = "q104",
    confession = "q98",
    religiosity = "q99",
    for_ag_army = "q69",
    for_ag_socspend = "q71",
    for_ag_eu = "q73",
    for_ag_foreign = "q75",
    for_ag_trad = "q77",
    for_ag_sec = "q79",
    for_ag_growth_over_env = "q81",
    for_ag_lthi = "q83",
    for_ag_nucl = "q85"
  ) %>% 
  mutate(
    education = if_else(education == 9, NA, education),
    private = if_else(q107 == 1, 1, 0),
    public = if_else(q107 == 2, 1, 0),
    retired_or_rent = if_else(occupation %in% c(6, 7), 1, 0),
    gender = case_when(
      sex == 1 ~ 0,
      sex == 2 ~ 1
    ),
    lab_union = if_else(q100 == 1, 1, 0),
    lr_recoded = case_when(
      lr %in% c(0,1,2) ~ "left",
      lr %in% c(3,4) ~ "center_left",
      lr == 5 ~ "center",
      lr %in% c(6,7) ~ "center_right",
      lr %in% c(8, 9, 10) ~ "right"
    ),
    left = if_else(lr_recoded == "left", 1,
                      if_else(is.na(lr_recoded), NA, 0)),
    center_left = if_else(lr_recoded == "center_left", 1,
                      if_else(is.na(lr_recoded), NA, 0)),
    center = if_else(lr_recoded == "center", 1,
                      if_else(is.na(lr_recoded), NA, 0)),
    center_right = if_else(lr_recoded == "center_right", 1,
                      if_else(is.na(lr_recoded), NA, 0)),
    right = if_else(lr_recoded == "right", 1,
                        if_else(is.na(lr_recoded), NA, 0))
  )

selects1995$age_cat <- cut(selects1995$age, c(18, 30, 45, 65, 99), right = FALSE, include.lowest = TRUE)

```


```{r}
cortest <- 
  selects1995 %>% 
  dplyr::select(matches("val[1-9]")) %>% 
  cor(method = "spearman", use = "complete.obs") %>% 
  cor.mtest()

selects1995 %>% 
  dplyr::select(matches("val[1-9]")) %>% 
  cor(method = "spearman", use = "complete.obs") %>% 
  corrplot.mixed(order = "hclust")

```


```{r}
setwd("F:/master-thesis/data")
write_sav(selects1995, "selects1995_recoded.sav")
```


