# Summary



```{r}
#| echo: false
#| warning: false
#| message: false
rm(list = ls())
library(tidyverse)
library(haven)
library(quarto)
library(sjlabelled)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(ade4)
library(questionr)
library(foreign)
library(MASS)
library("effects")
library(ordinal)
selects1995 <- read_sav("data/64_Selects1995_PES_Data_v1.2.sav")
selects <- read_sav("data/495_Selects_CumulativeFile_Data_1971-2019_v2.3.0.sav")
```


```{r}
selects1999 <- 
  selects %>% 
  filter(year == 1999)

freq(selects1999$vdn1b)

```

```{r}
selects1999 <- 
  selects1999 %>% 
  mutate(
    state_vs_market = case_when(
      ip5 == 0 ~ 1,
      ip5 == 0.25 ~ 2,
      ip5 == 0.5 ~ 3,
      ip5 == 0.75 ~ 4,
      ip5 == 1 ~ 5,
      is.na(ip5) ~ NA
    ),
    join_eu = case_when(
      ip6 == 0 ~ 1,
      ip6 %>% between(0.3, 0.4) ~ 2,
      ip6 %>% between(0.6, 0.7) ~ 3,
      ip6 == 1 ~ 4
    )
  )

selects1999$state_vs_market <- set_labels(selects1999$state_vs_market, labels = c("for state intervention", "rather for state intervention", "neither nor", "rather for free market", "for free market"))

selects1999$join_eu <- set_labels(selects1999$join_eu, labels = c("don't join", "rather don't join", "rather join", "join"))

selects1999 <- 
selects1999 %>% 
  rename(lower_t_hi = "ip2",
         uneq_chance_for = "ip9",
         quest_trad = "ip10",
         for_soc_exp = "ip13",
         env_vs_growth = "ip14",
         again_nucl = "ip15")

```


```{r}
freq(selects1999$lr1)

cortest <- 
  selects1999 %>% 
  select(state_vs_market, join_eu, lower_t_hi, for_soc_exp, eq_chance_for, env_vs_growth, quest_trad, again_nucl, income_hh, educ, lr1) %>% 
  cor(method = "spearman", use = "complete.obs") %>% 
  cor.mtest()

selects1999 %>% 
  select(state_vs_market, join_eu, lower_t_hi, for_soc_exp, eq_chance_for, env_vs_growth, quest_trad, again_nucl, income_hh, educ, lr1) %>% 
  cor(method = "spearman", use = "complete.obs") %>% 
  corrplot.mixed(order = "hclust", p.mat = cortest$p)


```


```{r}
acm <- 
selects1999 %>% 
  select(state_vs_market, join_eu, lower_t_hi, for_soc_exp, eq_chance_for, env_vs_growth, quest_trad, again_nucl, sex, income_hh, educ, religion, sg1, class8) %>% 
  as_character() %>% 
  as_factor() %>% 
  dudi.acm(scannf = FALSE, nf = 5)
```

```{r}
fviz_screeplot(acm, choice = "eigenvalue")
fviz_screeplot(acm)
s.corcircle(acm$co, 1, 2, clabel = 0.7)
fviz_mca_var(acm, repel = TRUE)
fviz_contrib(acm, choice = "var", axes = 1)
s.label(acm$co, clabel = 0.7)
```

```{r}
summary(ordreg <- polr(data = selects1999, as_factor(join_eu) ~ income_hh + educ + factor(sex), Hess = TRUE))

#Plotting the effects 
library("effects")
library(ordinal)
summary(ordreg2 <- clm(data = selects1999, as_factor(join_eu) ~ income_hh + educ + factor(sex), Hess = TRUE))
```

